Lazy/urls.py
from django.contrib import admin
from django.urls import path, include

from accounts.views import index_view
from main.views import chats_view, globe_view, profile_view
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index_view, name = 'login'),
    path('accounts/',include('accounts.urls')),
    path('main/', include('main.urls')),
    path('chats/', chats_view, name = 'chats'),
    path('globe/', globe_view, name = 'globe'),
    path('profile/', profile_view, name = 'profile')
]

main/forms.py
from django import forms

class ImageForm(forms.Form):
    image = forms.ImageField(label = '', widget = forms.FileInput(attrs={'class':'file_select_input'}))
    
class VideoForm(forms.Form):
    video = forms.FileField(label = '', widget = forms.FileInput(attrs={'class':'file_select_input','accept':'video/*'}))

templates/chats.html
{%extends 'index.html'%}
{%load static%}
{%block content%}
{%include 'navigations.html'%}
<div id="lazy_chat" class="long-tab full-height flex">
    <h4 class="lazy_h4 mt_5">chats</h4>

    {%for chat in chatlist%}
    <a href="{%url 'playground' chat.id %}" id="" class="chat_listing open_chat m_5 pb_10">
        <div class="lazy_chat_tab flex flex_row mt_5 ">
            <div class="profile_thum perfect_center"
            style = "
            background-image: url('{%if chat.first_user.user.id is myProfile.user.id %} {%static chat.last_user.profile_image_url %} {%else%} {%static chat.first_user.profile_image_url %} {%endif%}');
            background-size: cover;
            border-radius: 100%;
            ">
               
            </div>
            <div class="chat_content flex flex_col">
                <span class="msg_reciver">
                    {%if chat.first_user.user.id is myProfile.user.id%}
                     {{chat.last_user.user}}
                    {%else%}
                     {{chat.first_user.user}}
                    {%endif%}
                </span>
                <span class="last_msg"> 
                    {%if chat.first_user.user.id is myProfile.user.id%}
                     {{chat.last_user.user.last_login}}
                    {%else%}
                     {{chat.first_user.user.last_login}}
                    {%endif%}
                </span>
            </div>
        </div>
    </a>
    {%endfor%}

</div>

{%endblock%}

templates/globe.html
{%extends 'index.html'%}
{%load static%}
{%block content%}
{%include 'navigations.html'%}
<div id="lazy_contacts" class="full-height long-tab flex flex_col ">
    <h4 class="cnt_h4 mt_5">Global</h4>

    {%for Profile in globe%}
    {%if Profile.user.id is not myProfile.user.id %}
    <div class="contact_tab flex flex_row mt_5">
        <div class="contact_thumb" style="
        background-image: url('{%static Profile.profile_image_url %}');
        background-size: cover;
            border-radius: 100%;
        ">
            <!-- <img src="{%static Profile.profile_image_url %}" class="contact_image"> -->
        </div>
        <div class="contact_information ml_10 flex flex_col">
            <div class="contact_name">
                {{Profile.user.username}}
            </div>
            <div class="contact_actions perfect_center">
                <div class="perfect_center">
                    <!-- <a href="#" class="lazy_contact_icon m_10">
                        <i class="ion-ios-call"></i>
                    </a>
                    <a href="#" class="lazy_contact_icon m_10">
                        <i class="ion-ios-videocam"></i>
                    </a> -->
                    <a href="{%url 'new_chat' Profile.id %}" class="open_chat lazy_contact_icon m_10">
                        <i class="ion-ios-chatboxes"></i>
                    </a>
                </div>

            </div>

        </div>
    </div>
    {%endif%}
    {%endfor%}
</div>

{%endblock%}

templates/index.html
{%load static%}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="author" content="cXd llc" />
    <meta name="description" content="chat app" />
    <meta name="keywords" content="chat , lazy, lazy chat" />
    <link rel="stylesheet" type="text/css" href="{%static 'css/UI_design.css'%}" />
    <link rel="stylesheet" type='text/css' href="{%static 'css/animate.css'%}" />
    <link rel="stylesheet" type='text/css' href="{%static 'css/bootstrap.min.css'%}" />
    <link rel="stylesheet" type='text/css' href="{%static 'css/flaticon.css'%}" />
    <link rel="stylesheet" type='text/css' href="{%static 'css/ionicons.min.css'%}" />
    <script src="{%static 'js/jquery-3.2.1.min.js'%}"></script>
    <script src="{%static 'js/bootstrap.min.js'%}"></script>
    <script src="{%static 'js/easyDom2.0.js'%}"></script>
    <title>Lazy</title>
</head>

<body>
    <div class="full_height full_width flex flex_row">
        {%block content%}{%endblock%}
    </div>
    <div id="lazy_overlay" class="">
        <span class="online_dot float-right" style="position: absolute; left: 3px;" id="close_overlay">
            <i class="ion-md-arrow-back"></i>
        </span>
        <div id="lazy_content" class="lazy_overlay_content perfect_center"></div>
    </div>
    <script>

        $('.video_file').on("contextmenu", function () {
            var vid = newChild(getById("lazy_content"), "video", "video_overlayed", "media video_overlayed", "autoplay", "true")
            vid.src = this.src
            vid.controls = true
            $("#lazy_overlay").fadeIn()
            return false
        })

        $("img").on("contextmenu", function () {
            var img = newChild(getById("lazy_content"), "img", "video_overlayed", "media image_overlayed")
            img.src = this.src
            $("#lazy_overlay").fadeIn()
            return false;
        })

        // close overlay by double click
        $("#lazy_overlay").on("dblclick", function () {
            $("#lazy_overlay").fadeOut()
            getById("video_overlayed").src = undefined
            removeElement(getById("lazy_content"), getById("video_overlayed"))
        })
        $("#close_overlay").on("click", function () {
            $("#lazy_overlay").fadeOut()
            getById("video_overlayed").src = undefined
            removeElement(getById("lazy_content"), getById("video_overlayed"))
        })

        // play video file when clicked
        $("video").on("click", function () {
            if (!this.paused) {
                this.pause()
            } else {
                this.play()
            }
        })


    </script>
    <script src="{%static 'js/UI_design.js'%}"></script>
</body>

</html>

templates/login.html
{%extends 'index.html'%}
{%load static%}

{%block content%}
<div id="lazy_form" class="full-height bg-light fw">
    
    <div id="form_img_container" class="perfect_center">
        <img src="{% static 'img/lazy2dtext.png'%}" alt="lazy" id="lazy_login_img" />
    </div>

    <form action="." method="post" id="login_form">{%csrf_token%}
        <input type="text" name="username" id="username" placeholder="username" class="m_5 lazy_input" />
        <input type="password" name="password" id="password" placeholder="password" class="m_5 lazy_input" />
        <input type="submit" value="log in" id="submit_button" class="m_5" />
    </form>
    <a href="{%url 'signup'%}">Create Account</a>
    {{request.user}}
</div>
{%endblock%}

templates/navigations.html
<div id="lazy_navigation" class="long-tab full-height flex">
    <a href="{%url 'chats' %}" class="lazy_tab perfect_center mt_5" id="chats">
        <i class="ion ion-ios-chatboxes"></i>
    </a>
    <a href="{%url 'profile'%}" class="lazy_tab perfect_center mt_5" id="profile">
        <i class="ion ion-ios-person"></i>
    </a>
    <a href="{%url 'globe' %}" class="lazy_tab perfect_center mt_5" id="globe">
        <i class="ion-ios-globe"></i>
    </a>
    <a href="{%url 'logout' %}" class="lazy_tab perfect_center mt_5" id="logout">
        <i class="ion ion-ios-log-out"></i>
    </a>
</div>

templates/playground.html
{%extends 'index.html'%}
{%load static%}
{%block content%}
<script>
    var my_id = {{ myProfile.id }}
</script>
{%include 'navigations.html'%}

<div id="lazy_playground" class="long-tab full-height flex flex_col">
    <div class="messager_user_name fw">
        <span class="profile_actual_name">
            {%if active_chat.first_user.user.id is myProfile.user.id%}
            {{active_chat.last_user.user}}
            {%else%}
            {{active_chat.first_user.user}}
            {%endif%}
        </span>
        <span class="online_dot float-right">
            <i class="ion-ios-moon"></i>
        </span>
    </div>

    <div id="lazy_chat_room" class="fw">
        <!-- text messages -->

    </div>
    <div id="lazy_message_input" class="fw flex flex_row">
        <div class="lazy_tab_icon_container perfect_center m_5" id="attach">
            <i class="ion-ios-bowtie"></i>
        </div>
        <form method='POST' action="{%url 'send' active_chat.id %}" id="message_form" class="flex flex_col m_5">
            {%csrf_token%}
            <div class="flex_row flex">
                <input type="text" name="message" id="message_input_box" placeholder="Type here" />
                <input type='submit' class="ml_10" id="send_btn" value='send'>
            </div>

        </form>
    </div>

    <div id="options">

        <div class="fw flex flex_col">
            <div class="fw full-height perfect_center">
                <span id="back" class="attach_ico">
                    <i class="ion-md-arrow-back"></i>
                </span>
                <a href="{%url 'send_image' active_chat.id %}" id="image" class="attach_ico">
                    <i class="ion-ios-image"></i>
                </a>
                <a href="{%url 'send_video' active_chat.id %}" id="video" class="attach_ico">
                    <i class="ion-ios-videocam"></i>
                </a>

            </div>
        </div>



    </div>

</div>


<!-- jquery.ajax backend requests -->
<script>

    // more re-arrange

    //scroll to last message with chime sound
    var activetime = 0 //seconds active
    var ringtone = new Audio
    ringtone.src = "{%static 'ringtones/chimes.wav' %}"
    ringtone.volume = 1
    function ding() {
        ringtone.play()
    }

    function scroll_last() {
        var plate = getById('lazy_chat_room')
        var last = plate.lastElementChild
        var height = last.offsetTop
        plate.scrollTo(0, height + innerHeight)
    }

    //for message updating
    var initial = { id: 0 };
    var final = { id: 0 };

    //print messages when script loads
    collect_messages()
    //fetch new message after every second
    setInterval(function () {
        update_messages()
    }, 1000)
    

    function collect_messages() {
        $.ajax({
            type: 'GET',
            url: '{%url "get_messages" active_chat.id%}',
            success: function (response) {

                $("#lazy_chat_room").empty()
                for (key in response) {
                    var msgList = response[key]
                    for (var i = 0; i < msgList.length; i++) {
                        create_message(msgList[i])
                        initial = msgList[msgList.length - 1]
                    }
                }
                scroll_last()
            },
            error: function () {
                console.log('Error')
            }
        })
    }
    function update_messages() {
        $.ajax({
            type: 'GET',
            url: '{%url "get_messages" active_chat.id%}',
            success: function (response) {
                var msgList = null
                for (key in response) {
                    var msgList = response[key]
                    final = msgList[msgList.length - 1]
                }
                final = msgList[msgList.length - 1]
                if (final.id != initial.id) {
                    DOMCREATEMESSAGE(final)
                } else {
                    activetime++
                }
            },
            error: function () {
                console.log('Error')
            }
        })
    }
    function DOMCREATEMESSAGE(msg) {
        if (!getById('row_' + msg.id) ) {
            create_message(msg)
            scroll_last()
            initial = final
            if (msg.sender_id != my_id) {
                ding()
            }
        }

    }

    //sending text message
    $(document).on('submit', '#message_form', function (e) {
        e.preventDefault()
        if (getById("message_input_box").value != '') {
            $.ajax({
                type: 'POST',
                url: "{%url 'send' active_chat.id %}",
                data: {
                    content: $('#message_input_box').val(),
                    csrfmiddlewaretoken: $('input[name = csrfmiddlewaretoken]').val(),
                },
                success: function (data) {
                    getById("message_input_box").value = ''
                }
            })
        }

    })

    //deleting message
    function deleteMessage() {
        resp = confirm("delete?")
        if (resp) {
            alert('message delete function fall here --> ' + this.id)
        }

        return false
    }

    $(".file_input").hide()
    $("#options").hide()
    $("#attach").click(function () {
        $(".file_input").hide()
        $("#options").fadeIn()
    })
    $("#back").click(function () {
        $("#options").fadeOut()
    })

</script>
{%endblock%}

templates/profile.html
{%extends 'index.html'%}
{%load static%}
{%block content%}
{%include 'navigations.html'%}

<div id="lazy_profile" class=" long-tab full-height lazy_short_profile ">
    <div id="" class="profile_image_container perfect_center"
        style="background-image: url('{%static myProfile.profile_image_url %}');
        background-size: cover;width: 100%;height:300px">
    </div>
    <div class="profile_info_container perfect_center">
        <div class="more_info flex flex_col text-center">
            <span class="profile_actual_name">{{myProfile.user}}</span>
            <span class="profile_username">last login<br>{{myProfile.user.last_login}}</span>
        </div>
    </div>
</div>
{%endblock%}

templates/setup.html
{%extends 'index.html'%}
{%load static%}

{%block content%}
<div id="lazy_form" class="full-height bg-light">
    <div id="form_img_container" class="perfect_center">
      <img src="{%static 'img/lazy2dtext.png' %}" alt="lazy" id="lazy_login_img" />
    </div>

    <form action="" method="post" id="login_form" enctype="multipart/form-data">{%csrf_token%}
      {{form}}
      <input type="submit" value="Create profile" id="submit_button" class="m_5" />
    </form>
  </div>
{%endblock%}

templates/share_image.html
{%extends 'index.html'%}
{%load static%}

{%block content%}
<div id="lazy_form" class="long-tab full-height bg-light flex flex_col">
    <div id="img_container" class="perfect_center fw">
        <img src="{%static 'img/lazy2dtext.png' %}" alt="lazy" id="shared_img" style= "width: auto;max-width: 320px;height:auto;max-height: 500px"/>
    </div>

    <form action="" method="post" id="media_form" enctype="multipart/form-data" class="mt_10">{%csrf_token%}
        {{iForm}}
        <input type="submit" value="send" id="submit_button" class="m_5" />
    </form>

    <script>
        var file = null;
        var url = null;
        $('#id_image').change(function (e) {
            file = e.target.files[0]
            url = URL.createObjectURL(file)
            getById('shared_img').src = url;
        })

        
    </script>
</div>
{%endblock%}

templates/share_video.html
{%extends 'index.html'%}
{%load static%}

{%block content%}
<div id="lazy_form" class="long-tab full-height bg-light flex flex_col">
    <div id="img_container" class="perfect_center fw">
        <video src="{%static 'img/lazy2dtext.png' %}" alt="lazy" id="shared_img" style= "width: auto;max-width: 320px;height:auto;max-height: 500px"></video>
    </div>

    <form action="" method="post" id="media_form" enctype="multipart/form-data" class="mt_10">{%csrf_token%}
        {{vForm}}
        <input type="submit" value="send" id="submit_button" class="m_5" />
    </form>

    <script>
        var file = null;
        var url = null;
        $('#id_video').change(function (e) {
            file = e.target.files[0]
            url = URL.createObjectURL(file)
            getById('shared_img').src = url;
        })

        
    </script>
</div>
{%endblock%}

templates/signin.html
{%extends 'index.html'%}
{%load static%}

{%block content%}
<div id="lazy_form" class="full-height bg-light">
    <div id="form_img_container" class="perfect_center">
      <img src="{%static 'img/lazy2dtext.png' %}" alt="lazy" id="lazy_login_img" />
    </div>

    <form action="" method="post" id="login_form">{%csrf_token%}
      {{form}}
      <input type="submit" value="sign in" id="submit_button" class="m_5" />
      <script>
        $("#id_password2").on("input", function () {
          if ($("#id_password1").val() != $("#id_password2").val()) {
            $("#id_password2").css({ color: "red" });
          } else {
            $("#id_password2").css({ color: "#79391a" });
          }
        });
      </script>
    </form>
  </div>
{%endblock%}